"""add user_credentials table

Revision ID: 3be65f716e80
Revises: f276ed6b25cf
Create Date: 2026-08-10 18:06:57.565379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be65f716e80'
down_revision: Union[str, None] = 'f276ed6b25cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firecrawl_api_key', sa.String(length=255), nullable=True),
    sa.Column('telegram_bot_token', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_credentials_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_credentials'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credentials')
    # ### end Alembic commands ###
