"""add coupons table

Revision ID: 428470b3f9f8
Revises: 3be65f716e80
Create Date: 2026-08-11 11:17:09.321994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428470b3f9f8'
down_revision: Union[str, None] = '3be65f716e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('store_domain', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_coupons_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupons_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons'))
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_found_at'), ['found_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_store_domain'), ['store_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_user_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_store_domain'))
        batch_op.drop_index(batch_op.f('ix_coupons_product_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_found_at'))

    op.drop_table('coupons')
    # ### end Alembic commands ###
