"""widen telegram_chat_id to support multiple comma-separated ids

Revision ID: 584e8a55bf8b
Revises: 428470b3f9f8
Create Date: 2026-09-28 13:25:39.160189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584e8a55bf8b'
down_revision: Union[str, None] = '428470b3f9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.alter_column('telegram_chat_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
